### ISSUE TITLE
Export syntax

### ISSUE THREAD

**Issue by developerdizzle** [novemberborn/babel-plugin-import-glob#16]
Love this plugin!  Would be great to allow `export` syntax.  Eg:

``` js
export { foo, bar } from 'glob:*';
```

**Comment by novemberborn** [comment]
@developerdizzle thanks!

I think `export` syntax would be best in a different plugin, e.g. `babel-plugin-export-glob`. Feel free to use this one as a starting point if you want.

**Comment by celicoo** [comment]
This would be great!
