### ISSUE TITLE
Pathing issues?

### ISSUE THREAD

**Issue by amcdnl** [novemberborn/babel-plugin-import-glob#2]
Awesome module but I'm having a bit of trouble getting it working.  I was using glob before like this:

`const files = glob.sync(`./dist/api/**/*[Controller].js`);`

and I converted it to your code like:

`import * as filesz from 'glob:./dist/api/**/*[Controller].js';`

but the result is this from the console:

```
info: import globs {}
info: globs [ './dist/api/ApplicationController.js',
  './dist/api/RecordController.js',
  './dist/api/SearchController.js' ]
```

Your exports are pretty specific to your use case, I think it could benefit from making it more generic. Also you don't really explain the difference between what 'main' and '_partial' is.  Is partial the 'resolved' file? If so I'd recommend making a separate extension for that.

also would be cool to see integration with this: https://github.com/tleunen/babel-plugin-module-alias

**Comment by novemberborn** [comment]
> but the result is this from the console:

Which console are you referring to?

> Your exports are pretty specific to your use case, I think it could benefit from making it more generic.

It should be fairly generic already. What do you propose?

> Also you don't really explain the difference between what 'main' and '_partial' is. Is partial the 'resolved' file?

They refer to the `main.handlebars.js` and `_partial.handlebars.js` files in the `templates/` directory. Basically they're the identifiers for the matched files.

**Comment by amcdnl** [comment]
By console i mean `console.log`.

so I'm confused now, your exporting `{ main and _partial }`? are those module names? Glob normally returns an array of file paths not modules. 

By more generic I mean one for files and one for modules. so lke: `glob:**.js` would return `[ 'mypath/file.js' ]` vs `globResolve:**.js` would return `{ myFileModule }`

**Comment by novemberborn** [comment]
Ah! This plugin focuses on resolving the modules that match a glob pattern. In order to come up with an identifier to reference the module it cuts off parts of the path that are redundant, and then removes characters that cannot be used in an identifier.

I did start https://github.com/novemberborn/babel-plugin-files which gives an object with file information but that's not quite finished yet.

**Comment by amcdnl** [comment]
you should rename it then, to babel-plugin-glob-resolve or babel-plugin-resolve then ;)

**Comment by novemberborn** [comment]
It imports modules from a glob pattern, seems sufficient ;-)
