### ISSUE TITLE
pls plugin eslint

### ISSUE THREAD

**Issue by nililia** [novemberborn/babel-plugin-import-glob#35]
message: ''glob:routes' should be listed in the project's dependencies. Run 'npm i -S glob:routes' to add it (import/no-extraneous-dependencies)'at: '2,1' source: 'eslint'

**Comment by novemberborn** [comment]
You should be able to configure the `import` plugin to ignore `glob:` dependencies. [Configuring the rule itself](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md) may work, or perhaps through the [`no-unresolved`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unresolved.md) rule.

(I'm closing this issue but please feel free to discuss further.)
