### ISSUE TITLE
Are you using some sort of cache?

### ISSUE THREAD

**Issue by johanlajili** [novemberborn/babel-plugin-import-glob#52]
For some reason, when I add a new file in my folder (note that it is inside a node_modules folder), on rebuild it's not detected. For some reason I need to change the glob (for instance switch between
whatever/* and whatever/*.js).
So is there some sort of cache in your implementation that could cause that?
The bug happens with webpack and babel on my project. I don't really have time to create a standalone reproduce of the bug, but I just like to understand what might be causing it.

**Comment by novemberborn** [comment]
> The bug happens with webpack and babel on my project.

Either of those may be using a cache. As far as I know there's currently no way for this plugin to signal that the file should never be cached.

Re-saving the file that contains the glob may be sufficient, without actually having to make any changes. Sometimes it also helps to restart the webpack / Babel CLI watchers.

**Comment by pke** [comment]
yes it seems react-natives metro bundler also caches the modules resolved by this plugin and does not refresh them until resetting the cache. Thats kind of sad. It should not cache those dynamic modules... maybe it can be convinced to not cache certain module patterns.
