### ISSUE TITLE
New Fork

### ISSUE THREAD

**Issue by josheppinette** [novemberborn/babel-plugin-import-glob#57]
Hey everyone,

I needed some new features from this repo and since it seems to have stagnated, I have taken the existing code and done a complete simplification/refactor as well as added those features I needed. You can check it out here:

https://github.com/jteppinette/babel-plugin-import-glob/

**Comment by novemberborn** [comment]
Or you could submit a pull request? Maybe I'd give you commit access, you never know!

**Comment by josheppinette** [comment]
I changed up some functionality, so I wouldn’t want to break anything that existing users are relying on - unless we wanted to add those back.

Anyways, check out the code if you want to think about a merge.

**Comment by novemberborn** [comment]
That's what SemVer major is for.
